# Generated by Django 4.0.6 on 2022-07-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model1args'),
        ),
        migrations.AlterField(
            model_name='model1',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model10',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model10args'),
        ),
        migrations.AlterField(
            model_name='model10',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model10args',
            name='model2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model2'),
        ),
        migrations.AlterField(
            model_name='model10args',
            name='model4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model4'),
        ),
        migrations.AlterField(
            model_name='model10args',
            name='model7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model7'),
        ),
        migrations.AlterField(
            model_name='model10args',
            name='model8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model8'),
        ),
        migrations.AlterField(
            model_name='model2',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model2args'),
        ),
        migrations.AlterField(
            model_name='model2',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model3',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model3args'),
        ),
        migrations.AlterField(
            model_name='model3',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model4',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model4args'),
        ),
        migrations.AlterField(
            model_name='model4',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model5',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model5args'),
        ),
        migrations.AlterField(
            model_name='model5',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model5args',
            name='model4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model4'),
        ),
        migrations.AlterField(
            model_name='model6',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model6args'),
        ),
        migrations.AlterField(
            model_name='model6',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model6args',
            name='model4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model4'),
        ),
        migrations.AlterField(
            model_name='model7',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model7args'),
        ),
        migrations.AlterField(
            model_name='model7',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model8',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model8args'),
        ),
        migrations.AlterField(
            model_name='model8',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model8args',
            name='model1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model1'),
        ),
        migrations.AlterField(
            model_name='model8args',
            name='model2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model2'),
        ),
        migrations.AlterField(
            model_name='model8args',
            name='model7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model7'),
        ),
        migrations.AlterField(
            model_name='model9',
            name='args',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model9args'),
        ),
        migrations.AlterField(
            model_name='model9',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.csvdata'),
        ),
        migrations.AlterField(
            model_name='model9args',
            name='model1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model1'),
        ),
        migrations.AlterField(
            model_name='model9args',
            name='model8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.model8'),
        ),
    ]
